"""initial schema

Revision ID: 3032660616ee
Revises: 
Create Date: 2026-09-18 00:43:03.310180
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3032660616ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_actuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_centre', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('budget_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('variance_pct', sa.Float(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('narrative_approved', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abn', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('risk_tier', sa.String(), nullable=True),
    sa.Column('screening_notes', sa.Text(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('human_override', sa.String(), nullable=True),
    sa.Column('onboarding_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_abn'), ['abn'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_bank_account'), ['bank_account'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('human_override', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('cost_centre', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))

    op.drop_table('purchase_orders')
    op.drop_table('invoices')
    op.drop_table('audit_log')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_bank_account'))
        batch_op.drop_index(batch_op.f('ix_vendors_abn'))

    op.drop_table('vendors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('budget_actuals')
    # ### end Alembic commands ###
